name: build and deploy app 
on:
  push: 
   branches:
        - main 

jobs:
   build-deploy:
         name: build and deploy spring app
         runs-on: ubuntu-latest
         steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: setup JDK-17
              uses: actions/setup-java@v3
              with: 
                distribution: 'corretto'
                java-version: 17
            - name: unit tests
              run:  mvn -B test --file pom.xml 
            - name: build app
              run: | 
                mvn clean
                mvn -B package --file pom.xml
            - name: build docker image
              uses: docker/build-push-action@v2
              with: 
                    context: .
                    dockerfile: Dockerfile
                    push: false
                    tags: ${{secrets.DOCKER_HUB_USR}}/spring-boot-for-beginners:latest
            - name: login to docker hub 
              uses: docker/login-action@v1
              with:
                    username: ${{secrets.DOCKER_HUB_USR}}
                    password: ${{secrets.DOCKER_HUB_TOKEN}}
            - name: push to docker hub
              uses: docker/build-push-action@v2
              with: 
                    context: .
                    dockerfile: Dockerfile
                    push: true
                    tags: ${{secrets.DOCKER_HUB_USR}}/spring-boot-for-beginners:latest



